-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: requirements-txt-fixer
    -   id: check-ast
    -   id: fix-encoding-pragma
